name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        node:
        # node 12.18 has a regression
        # npm ERR! cb.apply is not a function
        # - 12
        - 12.17
        # node 14.5 has a regression
        # npm ERR! cb.apply is not a function
        # - node
        - 14.4

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci
    - run: npm test
      env:
        DEBUG: create-react-app-updater,boilerplate-update,git-diff-apply

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v2

    - uses: kellyselden/ember-cli-update-action@v3
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
