name: CI

on:
  # allow manual running
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        node:
        - 16

        - node

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - run: which npx
    # don't accidentally use the global npx
    - run: rm $(which npx)
    # sometimes this exists
    - run: rm /usr/local/bin/npx || true
    # test that we can't find it
    - run: "! which npx"

    - run: npm ci
    - run: npm test
      env:
        DEBUG: create-react-app-updater,boilerplate-update,git-diff-apply

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    - uses: kellyselden/ember-cli-update-action@v4
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
